notifications:
  email: false
language: c #NOTE: this will set CC=gcc which might cause trouble

before_script:
  - WGET="travis_retry wget --continue --tries=20 --waitretry=10 --retry-connrefused --no-dns-cache --timeout 300"
  - sudo apt-get -qq update
  - export PROJ_ROOT=$(pwd)

  ## Install doxygen
  - if [ ${BUILD_CATEGORY:-0} = doxygen ] ; then
      sudo add-apt-repository ppa:libreoffice/libreoffice-4-4 -y && sudo apt-get -qq update &&
      sudo apt-get --no-install-suggests --no-install-recommends -qq install doxygen  &&
      doxygen --version ;
    fi

  ## Install avr toolchain
  - sudo apt-get -qq install gcc-avr avr-libc

  ## Install 32-bit compatibility libraries
  - sudo apt-get -qq install libc6:i386 libgcc1:i386 gcc-4.6-base:i386
      libstdc++5:i386 libstdc++6:i386


script:
  ## regression-tests/Makefile handles most of generic logic
  - "make -C tests/$BUILD_TYPE all"

 
after_success:
    # Create doxygen documentation
    - cd $PROJ_ROOT
    - doxygen docs/Doxyfile > /dev/null

    # publish doxygen documentation
    - ./deploy-ghpages.sh

env:
  global:
  - GH_REF = github.com/brtos/brtos.git
  - secure = "RQW6JLQGhylTZ3P9SZywApgPurhC0qZ4ymHqA4/yk2NVPL0xX1XMBR6c5UUoJbOmPHeTxOdvdD+mZ9yDu3XuFUwUxmKap/Il1d7SoCUcM70U7p4Dsdfjt/1/ejAkVzmm7SVNSRWi4hczJnG0l93FY/8+hwDUpZsl8ifz1XIE7n1DE1Bn+TirPl5Zy654AJFxA/CLnGqSxFnezlt+GJdXGwPVjB8Qo/87r57fAzcvkpbyRlMwTyAx4RACNUqAWskm3reJD34+Bu+i8rKRHh8kvwEiPeVi/UnZuFuWOtMvBNGrvhwDm9azr+KWBaBhU/BU7XcMHlqItIHiizywaq0L1JMdIF+udooBmOEEp2SZn8uUoymRH2rtxL6gPVesrAQxAK/zSR6dsuV6O//AUQeHnsOBBhvgDGNNtEQ9d+Xgsm2PvlZY8NO2Ri4nkkVSHTC3mjv2smkSJrYq6o0vguF0JV6A+3KCzFYVtnMZbu9Vfkw5Agg1lg/69W61HxdVRPjzcAE2B5sJaiY88NqrUTIAfW18iOKYnQ6njzXRsyzyia+FHyL+GxKIwNWrYej8gBF75eaVmQyKHyL6xQLpQHbw7yIr0JvSLdU4KtLce9l3JcHZrSbRgAZQPeEAq76RWEzexcWfhwgL88lp98gl8fhSt8tBWfelScqauFwDQkEfm/o="
  
  ## This magically kick-off parallel jobs for each of the for the sets
  ## of environment variable defined below
  - BUILD_TYPE='doxygen'  BUILD_CATEGORY='doxygen'

